### ISSUE TITLE
Support .frq.gz

### ISSUE THREAD

**Issue by mmoisse** [kindlychung/collapsabel2#1]
Could you add support to gzipped frequency files?

Tx

**Comment by kineticz** [comment]
Could you elaborate on the use case?

**Comment by mmoisse** [comment]
When you run the command below to perform the gwas, you need several files amongst which the test.frq file. Now this file is relatively big in size (~8% of the test.bed file) and can easily be reduced by gzipping the files (to ~0.5% of the test.bed file). Additionally plink has an option when creating the frequency file to direly gzip is to test.frq.gz using: plink --noweb --bfile test --freq gz --out test

But if I run the command below with the gzipped version of the freq file (test.frq.gz) the command halts because it can not find test.frq. 

Now my question was if it would be possible to change the code in such a way that both file formats test.frq and test.frq.gz would be supported?
This is not a life-threatening issue but rather an optimization suggestion.

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)
pl_gwas = plGwas(rbed_info,
    pheno = "test.phe",
    pheno_name = "y",
    covar_name = "sex,age",
    gwas_tag = "test_y_sex_age")
gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Comment by kineticz** [comment]
Did you see any error message? This might be a bug. Thanks for reporting!

**Comment by kineticz** [comment]
To be specific, it shouldn't matter at all whether the .frq file exists, CollapsABEL should be able to create it when necessary. I would first check whether plink is on your `$PATH`. 

WRT .gz format, I don't think it really matters. It's used to collect some info, basically, after `rbed_info = rbedInfo(bedstem = "test", TRUE)` you should be able to even delete it without much concern.

**Comment by kineticz** [comment]
Also, plink2 is what we used in all our tests: https://www.cog-genomics.org/plink2

**Comment by mmoisse** [comment]
I also used plink2, I encountered this issue by diving into your code, because I got the error message:
plink failed.
In the end it turned out that the test.frq file was not causing the error but something else (I will post a different issue)

But anyway I did found an issue with test.frq.
This is what I did:

**In terminal:**

```
cd /tmp
wget https://bitbucket.org/kindlychung/collapsabel/downloads/testfiles.zip
unzip -o testfiles.zip
rm testfiles.zip
cd CollapsABEL_test
```

**In R:**

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)
pl_gwas = plGwas(rbed_info,
        pheno = "test.phe",
        pheno_name = "y",
        covar_name = "sex,age",
        gwas_tag = "test_y_sex_age")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
## Remove the frq file
unlink("test.frq")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Error message**
`Error in if (isSetup(pl_info)) { : missing value where TRUE/FALSE needed`

Even if I close R and restart it I get the same error:
**In R:**

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)
```

**Error message**
`Error in if (isSetup(pl_info)) { : missing value where TRUE/FALSE needed`

**Comment by kineticz** [comment]
Ah, yes indeed, the timestamp of .frq file is used for checking whether the sqlite database is up-to-date.  

But I am not terribly motivated to save a little disk space, they are inexpensive and increasingly so. 

Will close this for now, if you have further issues, please vote to reopen.
