### ISSUE TITLE
Set tmp file path

### ISSUE THREAD

**Issue by mmoisse** [kindlychung/collapsabel2#2]
Is there a way to set the temp filepath?

I'm working on a cluster where I have a quota of 8GiB in my homedir. When I run multiple instances of CollapsABEL they all crash due to I/O error. I noticed that this is due to the fact that CollapsABEL makes temp files in in ${HOME}/.collapsabel/
I solved this by making ${HOME}/.collapsabel a symlink to a place without space quota. But it would be nice it this would a setting somewhere.

**Comment by kineticz** [comment]
Yes, like this:

```
library(CollapsABEL)
collenv$.collapsabel_dir = "/tmp/collapsabel"
rbed_info = rbedInfo(bedstem = "test", TRUE)
pl_gwas = plGwas(rbed_info,
pheno = "test.phe",
pheno_name = "y",
covar_name = "sex,age",
gwas_tag = "test_y_sex_age")
gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Comment by kineticz** [comment]
I forgot something, there are two other variables that can also be changed: 

```
collenv$.collapsabel_dir = "/tmp/colldir"
collenv$.collapsabel_gwas = file.path(collenv$.collapsabel_dir, "gwas")
collenv$.collapsabel_gcdh = file.path(collenv$.collapsabel_dir, "gcdh")
```
