### ISSUE TITLE
Issues with binary dependant variables

### ISSUE THREAD

**Issue by mmoisse** [kindlychung/collapsabel2#3]
I'm getting errors what I used binary (0/1) variables as dependable variables.

**Error message**
`Error in validObject(.Object) : invalid class “FilePath” object: Missing file /home/user/.collapsabel/gwas/test_gc_sex_age_pExsUh/test.assoc.logistic`

I could solve it by converting the 0/1 coding to 1/2 coding, but it broke again when the first observation was NA.

This is what I did:

**In terminal:**

```
cd /tmp
wget https://bitbucket.org/kindlychung/collapsabel/downloads/testfiles.zip
unzip -o testfiles.zip
rm testfiles.zip
cd CollapsABEL_test
```

**In R:**

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)
pl_gwas = plGwas(rbed_info,
        pheno = "test.phe",
        pheno_name = "gc",
        covar_name = "sex,age",
        gwas_tag = "test_gc_sex_age")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Error message**
`Error in validObject(.Object) : invalid class “FilePath” object: Missing file /home/user/.collapsabel/gwas/test_gc_sex_age_pExsUh/test.assoc.logistic`

---

Recode 0/1 into 1/2

**In R:**

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)

pheno <- read.table("test.phe", header=T)
pheno$gc <- pheno$gc + 1
write.table(pheno, file="test.12.phe", quote=F, row.names=F, col.names=T, sep=" ")

pl_gwas = plGwas(rbed_info,
        pheno = "test.12.phe",
        pheno_name = "gc",
        covar_name = "sex,age",
        gwas_tag = "test_gc_sex_age")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Error message**
No error messages this time

---

Set first observation to NA

**In R:**

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)

pheno <- read.table("test.phe", header=T)
pheno$gc <- pheno$gc + 1
pheno$gc[1] <- NA
write.table(pheno, file="test.12NA.phe", quote=F, row.names=F, col.names=T, sep=" ")

pl_gwas = plGwas(rbed_info,
        pheno = "test.12NA.phe",
        pheno_name = "gc",
        covar_name = "sex,age",
        gwas_tag = "test_gc_sex_age")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Error message**
`Error in validObject(.Object) : invalid class “FilePath” object: Missing file /home/user/.collapsabel/gwas/test_gc_sex_age_1862EZ/test.assoc.linear`

**Comment by kineticz** [comment]
Would you mind posting a small dataset so that I can reproduce the error? Thanks!

**Comment by mmoisse** [comment]
I used your dataset (https://bitbucket.org/kindlychung/collapsabel/downloads/testfiles.zip) to cause the error. If you follow all the terminal and R steps you should get the same errors:

**Comment by kineticz** [comment]
Following PLINK conventions, all phenotypes must be numerically coded, including missing values, in the alternate phenotype file. The default missing value is -9.

**Comment by kineticz** [comment]
In the case of binary phenotypes, 1 means unaffected, 2 means affected, both 0 and -9 stand for missing. I will update the doc.

**Comment by kineticz** [comment]
Please try the latest master and let me if there is a problem.

**Comment by kineticz** [comment]
Here is what I tested: 

```
library(CollapsABEL)
rbed_info = rbedInfo(bedstem = "test", TRUE)

pheno <- read.table("test.phe", header=T)
pheno$gc <- pheno$gc + 1
pheno$gc[1] <- -9
write.table(pheno, file="test.12NA.phe", quote=F, row.names=F, col.names=T, sep=" ")

pl_gwas = plGwas(rbed_info,
        pheno = "test.12NA.phe",
        pheno_name = "gc",
        covar_name = "sex,age",
        gwas_tag = "test_gc_sex_age")

gcdh_res = runGcdh(pl_gwas, n_shift = 5)
```

**Comment by mmoisse** [comment]
With the latest master it runs fine. Tx!
